on: push
name: Slack Notification Demo
jobs:
    slackNotification:
      name: Slack Notification Demo
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Slack Notification Demo
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
          SLACK_MESSAGE: 'Repo: ${{ github.repository }} Push: ${{github.actor}} Url: prod-8dee7.web.app'
          SLACK_TITLE: 'From Github'
          SLACK_CHANNEL: 'firebase'
